### PR TITLE
Bevy 0.13

### PR DESCRIPTION
**Pull request by ghost**
Port to bevy 0.13

Followed this guide: https://bevyengine.org/learn/migration-guides/0-12-to-0-13/

Both examples in `examples/` compile.

**Marked as draft due to the following issue**: Color is set for meshes to `Color::SALMON` in examples as before, but it does not work. The meshes in both examples are completely black instead. No idea why.

### CODE REVIEW

**Comment by Adamkob12** [comment]
Thank you very much!
I tried looking into why the meshes are black, I didn't find an answer. But I do want this merged, because this is important. So let's just add something like:
```rust
app.insert_resource(ClearColor( // Some color you want, to stand out against the black mesh );
```
So the black meshes don't blend into the background, I think it's good enough for now.

And we'll leave the meshes' color as a separate issue.

**Review by Adamkob12 — CHANGES_REQUESTED** [review]
LGTM
Just add
```
app.insert_resource(ClearColor(..));
```
so the meshes are better visible

**Comment by ghost** [comment]
I did the good old "comment things out until the issue goes away to see what breaks it" trick and landed on `AmbientLight`. Then looked at the migration guide and it says that the default brightness for it is now `80.0`, so the `0.3` and `1.5` which was decently bright in Bevy 0.12 is now completely black in 0.13. 

Bumped the brightness for both and seems fine now.

**Review by Adamkob12 — APPROVED** [review]
LGTM, well done.

**Pull request merged**
